### ISSUE TITLE
why not using build-in hostfile-update

### ISSUE THREAD

**Issue by zh99998** [confirm/edgerouter-dnsmasq-updater#2]
there is a `service dhcp-server hostfile-update` option, just set it to enable and all things will done.

**Comment by domibarton** [comment]
Yeah there is and it might work for a lot of users. However, there are two problems with it:

1. It's a security issue when the client can set its own hostname ;) It's kinda DNS hijacking, isn't it?
2. If you've two hosts with the same hostname, you've a problem. This happens a lot, especially for appliances such as SONOS, weather stations, TV's and many more.

This would be an awesome feature if EdgeOS only sets hostnames for static DHCP leases, but since it will also do it for non-static DHCP leases, it's a bit of a PITA. Especially if you've a "guest" VLAN and guests can replace your DNS entries.

Long story, short: Good idea, bad implementation (IMHO).
